### ISSUE TITLE
workflows: doubling test runs

### ISSUE THREAD

**Issue by pared** [iterative/cookiecutter-dvc-plugin#2]
In https://github.com/iterative/dvc-render/runs/6265732010?check_suite_focus=true
we can see that the builds are doubled (one for PR, one for push). We should investigate if we could avoid that.

**Comment by casperdcl** [comment]
This bugs me too in many places.

Maybe https://github.com/fkirc/skip-duplicate-actions?

**Comment by pared** [comment]
This seems nice! Seems like besides skipping duplicate runs we could specify which file updates don't need running tests. I think that in the case of README and cosmetic changes that could be useful too.

**Comment by skshetry** [comment]
I think you meant to create this in `py-template`. We fixed this in https://github.com/iterative/py-template/pull/59, and the `dvc-render` has been synced with the template in https://github.com/iterative/dvc-render/pull/76.
